templates:
  - template6.json
modules:
  - UltrasonicModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: false
      textFrequency: 60
  - MapModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: false
      textFrequency: 60
  - CounterModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: false
      textFrequency: 60
logDirectory: