templates:
modules:
  - UltrasonicModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: true
      textFrequency: 60
  - MapModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: true
      textFrequency: 60
  - CounterModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: true
      textFrequency: 60
logDirectory: