templates:
modules:
  - UltrasonicModule:
      graphicsLogEnabled: true
      graphicsFrequency: 0
      textLogEnabled: true
      textFrequency: 0
  - MapModule:
      graphicsLogEnabled: true
      graphicsFrequency: 0
      textLogEnabled: true
      textFrequency: 0
  - CounterModule:
      graphicsLogEnabled: true
      graphicsFrequency: 0
      textLogEnabled: true
      textFrequency: 0
logDirectory: