templates:
modules:
  - UltrasonicModule:
      graphicsLogEnabled: true
      graphicsFrequency: 60
      textLogEnabled: false
      textFrequency: 60
  - MapModule:
      graphicsLogEnabled: true
      graphicsFrequency: 120
      textLogEnabled: false
      textFrequency: 60
  - CounterModule:
      graphicsLogEnabled: false
      graphicsFrequency: 60
      textLogEnabled: false
      textFrequency: 60
logDirectory: