templates:

modules:
  - UltrasonicModule:
      graphicsLogEnabled: true
      graphicsFrequency: 500
      textLogEnabled: false
      textFrequency: 60
  - MapModule:
      graphicsLogEnabled: true
      graphicsFrequency: 500
      textLogEnabled: false
      textFrequency: 60
  - CounterModule:
      graphicsLogEnabled: true
      graphicsFrequency: 500
      textLogEnabled: false
      textFrequency: 60
logDirectory: