templates:
  - template3.json
  - template4.json
  - template5.json
modules:
  - UltrasonicModule:
      graphicsLogEnabled: false
      graphicsFrequency: 0
      textLogEnabled: false
      textFrequency: 0
  - MapModule:
      graphicsLogEnabled: false
      graphicsFrequency: 0
      textLogEnabled: false
      textFrequency: 0
  - CounterModule:
      graphicsLogEnabled: false
      graphicsFrequency: 0
      textLogEnabled: false
      textFrequency: 0
logDirectory: